services:
  llmfabric:
    image: ${IMAGE_REGISTRY:-docker.io}/${IMAGE_NAMESPACE:-6block}/llmfabric:${LLMFABRIC_TAG:-latest}
    container_name: llmfabric
    restart: unless-stopped
    volumes:
      - llmfabric-data:/var/lib/llmfabric
    ports:
      - "8888:80"

volumes:
  llmfabric-data: {}
