{
 "title": "LLMFabric Worker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(gpustack:cluster_info,cluster_name)"
    }
   },
   {
    "name": "worker_name",
    "label": "Worker",
    "query": {
     "query": "label_values(gpustack:worker_status{cluster_name=\"$cluster_name\"},worker_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gpustack:worker_node_os_info{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "Total Workers"
    },
    {
     "expr": "count(gpustack:worker_node_gpu_cores{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "Total GPUs"
    }
   ]
  },
  {
   "title": "Average GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpustack:worker_node_gpu_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average VRAM Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpustack:worker_node_gram_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpustack:worker_node_gpu_temperature_celsius{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpustack:worker_node_gram_total_bytes{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpustack:worker_node_memory_total_bytes{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpustack:worker_node_cpu_cores{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "gpustack:worker_node_gpu_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpustack:worker_node_gram_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpustack:worker_node_gpu_temperature_celsius{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gpustack:worker_node_memory_used_bytes{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpustack:worker_node_gpu_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "{{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    }
   ]
  },
  {
   "title": "VRAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpustack:worker_node_gram_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "{{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpustack:worker_node_cpu_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gpustack:worker_node_gram_total_bytes{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "Total: {{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    },
    {
     "expr": "gpustack:worker_node_gram_used_bytes{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "Used: {{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    },
    {
     "expr": "gpustack:worker_node_gram_allocated_bytes{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "Allocated: {{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpustack:worker_node_gpu_temperature_celsius{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}",
     "legendFormat": "{{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (cluster_name,worker_name,gpu_chip_index,gpu_index) (gpustack:worker_node_gpu_utilization_rate{cluster_name=~\"$cluster_name\",worker_name=~\"$worker_name\"}) ",
     "legendFormat": "{{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    }
   ]
  },
  {
   "title": "VRAM Utilization",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (cluster_name,worker_name, gpu_chip_index,gpu_index) (gpustack:worker_node_gram_utilization_rate{cluster_name=\"$cluster_name\",worker_name=~\"$worker_name\"}) ",
     "legendFormat": "{{worker_name}} GPU{{gpu_index}} (chip {{gpu_chip_index}})"
    }
   ]
  }
 ]
}